openapi: "3.0.0"

info:
  title: "Translator"
  description: "API that accepts a text string and returns the same text string translated into another language."
  version: "1.0"

paths:
  /extractsourcestring:
    post:
      description: "Json with single field containing text in the source language."
      responses:
        '200':
          description: "Returns user-provided string in source language."
          required: true
          content:
            text/plain:
              schema:
                type: string
